#!/bin/bash
#edit here according to your needs
interface="gtk"
usrname="oliver"
clang="true"
config_vimrc="true"
easytags="true"
latex="true"
dir="~/.vim"

#what's left to do
#move script to python

apt-get -y update
apt-get -y upgrade

apps="git exuberant-ctags curl libpython2.7-dev"
apt-get install $apps

if [ "$interface" == "gtk" ]
then 
echo "$interface"
apt-get -y install vim-gtk
elif [ "$interface" == "gnome" ]
then
echo "$interface"
apt-get -y install vim-gnome
else 
echo "Unknown"
fi

if [ "$config_vimrc" == "true" ]
then
cp vimrc /etc/vim/vimrc
fi

#package manager
#have to include python script to generate vimrc
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

cd  /home/$usrname/.vim/bundle
# my favourite color scheme 
git clone https://github.com/christophermca/meta5.git 
#text based vim gdb intercreation
git clone https://github.com/vim-scripts/Conque-GDB.git 
#the nerd tree
git clone https://github.com/scrooloose/nerdtree.git
#nerd-tree-tabs
git clone https://github.com/jistr/vim-nerdtree-tabs.git
#c-vim 
git clone https://github.com/vim-scripts/c.vim.git

if [ "$easytags" == "true" ]
then
#vim-misc needed for easy-tags
git clone https://github.com/xolox/vim-misc.git
#vim-easy-tags
git clone https://github.com/xolox/vim-easytags.git 
fi


if [ "$clang" == "true" ]
then
#we have to implement logic to determine current clang version here
ver="3.7"
apt-get install clang-$ver clang-format-$ver cmake
ln -s /usr/bin/clang-$ver /usr/bin/clang
ln -s /usr/bin/clang++-$ver /usr/bin/clang++
#change i386 to x86 64 whatever
ln -s /usr/lib/x86_64-linux-gnu/libclang-$ver.so /usr/lib/libclang.so
cd  /home/$usrname/.vim/bundle
#clang-format
git clone https://github.com/rhysd/vim-clang-format.git
#ycm
git clone https://github.com/Valloric/YouCompleteMe.git
cd YouCompleteMe
git submodule update --init --recursive
./install.py --clang-completer

#ycm generator
cd /home/$usrname/.vim/bundle
git clone https://github.com/rdnetto/YCM-Generator.git

else 
echo "Non clang mode" 
fi 

if [ "$latex" == "true" ]
then
#vim-latex
wget -c http://sourceforge.net/projects/vim-latex/files/snapshots/vim-latex-1.8.23-20141116.812-gitd0f31c9.tar.gz
tar -xvzf vim-latex-1.8.23-20141116.812-gitd0f31c9.tar.gz
fi

echo "To access all help files restart vim and run :Helptags"

