#!/bin/bash
interface="gtk"
usrname="oliver"
clang="true"
latex="true"
dir="~/.vim"

#what's left to do
#move script to python
#for debian 8 clang ver 3.7/other 3.6 min 3.5
#change i386 x86_64

#apt-get -y update
#apt-get -y upgrade

apps="git python2.7 exuberant-ctags curl"
apt-get install $apps

#package manager
#have to include python script to generate vimrc
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim


if [ "$clang" == "true" ]
then
#we have to implement logic to determine current clang version here
ver="3.6"
apt-get install clang-$ver clang-format-$ver cmake
ln -s /usr/bin/clang-$ver /usr/bin/clang
ln -s /usr/bin/clang++-$ver /usr/bin/clang++
#change i386 to x86 64 whatever
ln -s /usr/lib/i386/libclang-$ver.so /usr/lib/libclang.so
cd  /home/$usrname/.vim/bundle
#clang-format
git clone https://github.com/rhysd/vim-clang-format.git
#ycm
git clone https://github.com/Valloric/YouCompleteMe.git
cd YouCompleteMe
git submodule update --init --recursive
#TODO: there is a problem with libclang
#maybe we have to download libclang extern
./install.py --clang-completer --system-libclang

#ycm generator
cd /home/$usrname/.vim/bundle
git clone https://github.com/rdnetto/YCM-Generator.git

else 
echo "Non clang mode" 
fi 

if [ "$latex" == "true" ]
#https://github.com/lervag/vimtex.git http://sourceforge.net/projects/vim-latex/files/
#http://vim-latex.sourceforge.net/index.php?subject=download&title=Download
#apt-get install texlive-full texlive-extra-utils
#

fi

if [ "$interface" == "gtk" ]
then 
echo "$interface"
#apt-get -y install vim-gtk
elif [ "$interface" == "gnome" ]
then
echo "$interface"
apt-get -y install vim-gnome
else 
echo "Unknown"
fi